import type { Metadata } from "next";
import { Vollkorn } from "next/font/google";
import "./globals.css"
import Header from "@/components/header";

const vollkorn = Vollkorn({
  variable: "--font-vollkorn",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`max-w-4xl mx-auto ${vollkorn.className} antialiased py-9 px-3`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
